model:
  base_learning_rate: 4.5e-6
  params: 
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      disc_start: 0
      kl_weight: 0.000001
      disc_weight: 0.5
    ckpt_path: "kl-f4/model.ckpt"
    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0



data:
  batch_size: 8
  num_workers: 2
  train:
      data_root: "data/xray/train"
      size:  256
    # validation:
    #   target: ldm.data.xray.XrayDataset
    #   params:
    #     data_root: "data/xray/valid"
    #     size:  256

# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 12
#     wrap: True
#     train:
#       target: ldm.data.imagenet.ImageNetSRTrain
#       params:
#         size: 256
#         degradation: pil_nearest
#     validation:
#       target: ldm.data.imagenet.ImageNetSRValidation
#       params:
#         size: 256
#         degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      batch_frequency: 1000
      max_images: 8
      increase_log_steps: True
    


  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    accelerator: "gpu"
    devices: 2
    num_nodes: 1
    # precision: 16
  # trainer:
  #   benchmark: True
  #   accumulate_grad_batches: 2
  #   accelerator: "tpu"
  #   devices: 8
    # precision: 16

